services:
  web:
    image: docker.hypernode.com/byteinternet/hypernode-buster-docker-php82-mysql80:latest
    ports:
      - 8080:80
    links:
      - es
    volumes:
      - ./src:/data/web/public
      - ./magento-bin:/opt/magento-bin
      - ~/.composer/cache:/var/www/.composer/cache
      - ~/.composer/auth.json:/var/www/.composer/auth.json
  es:
    image: elasticsearch:7.17.5
    ports:
      - 9200
    environment:
        - discovery.type=single-node
